### PR TITLE
Fixes #23 Support for target.classNames

### LINKED ISSUE #23: Allow className attributes to be passed on targets (tiles)
Impact needs to be able to specify that a tile be selected.

### PR DESCRIPTION
**Pull request by codecounselor**
Fixes #23

### CODE REVIEW

**Comment by codecounselor** [comment]
On the impact side 

image

image

**Comment by nathanbowser** [comment]
@codecounselor I published v2.6.0 i can bump it in impact, let me know which branch.

**Comment by codecounselor** [comment]
2021-commercial, thanks

**Review by donald-john — COMMENTED** [review]
+1

**Pull request merged**
