### PR TITLE
Enable bootslide tile sections

### PR DESCRIPTION
**Pull request by donald-john**
We need the ability to create labeled sections inside the tiled bootslide menus for https://github.com/SpiderStrategies/Scoreboard/issues/27069
This enables us to pass sections in to accomplish that

### CODE REVIEW

**Comment by nathanbowser** [comment]
+1, but I've been out of the bootslide game for quite a long time, so I'd trust @jerryorr 's review over mine.

**Comment by nathanbowser** [comment]
I'll merge and cut a release.

**Comment by nathanbowser** [comment]
@donald-john I'll bumped bootslide in Impact. Should I bump it in 2021-commercial or a specific branch of yours?

**Comment by donald-john** [comment]
@nathanbowser you can go ahead and bump it in 2021-commercial

**Comment by nathanbowser** [comment]
@donald-john Done!

**Pull request merged**
